# Generated by Django 5.0 on 2023-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=70)),
                ('rcategory', models.CharField(max_length=50)),
                ('rarea', models.CharField(max_length=50)),
                ('rdrink', models.CharField(max_length=50)),
                ('rinstruction', models.TextField()),
            ],
        ),
    ]
