# Generated by Django 5.0 on 2023-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rvideoLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
